### ISSUE TITLE
Ok so, when I try to use this plugin to make the player go to a multiverse world, I can't find out what to put in the "player" space because %p% does not work.

### ISSUE THREAD

**Issue by EchoNoahGaming** [LichtHund/CitizensCMD#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Citizens version
 - Spigot version
 - CitizensCMD version
- Java version

**Additional context**

**Comment by LichtHund** [comment]
Have you tried %player%? Or even using PlaceholderAPI?
