### ISSUE TITLE
Link to save.yml converter is broken

### ISSUE THREAD

**Issue by Klawdek** [LichtHund/CitizensCMD#13]
**Describe the bug**
The link on the page about migrating from 1.2.2 to 2.0 is broken
**To Reproduce**
check it here:
https://github.com/ipsk/CitizensCMD/wiki/Migrating-from-CitizensCMD-1.2.2-to-CitizensCMD-2.0

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Citizens version
 - Spigot version
 - CitizensCMD version
- Java version

**Additional context**

**Comment by LichtHund** [comment]
Thank you for letting me know, I've been looking into it and rewriting it a bit, it'll hopefully be back soon, sorry for taking so long.
