### ISSUE TITLE
per-npc requirements

### ISSUE THREAD

**Issue by exp153** [LichtHund/CitizensCMD#15]
**Is your feature request related to a problem? Please describe.**
There is no way to allow players access to certain NPCs based on rank, permissions, balance, etc.

**Describe the solution you'd like**
The creation of interaction requirements - allow interaction with NPCs based on permissions, balance (Vault), rank, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LichtHund** [comment]
Not sure if this is what you mean, but, there is a permission `citizenscmd.use`, that you can negate to the ranks you don't want to use the NPC, and there is also a price option that you can set to the NPC.
If you're talking about per NPC use permission than it's not possible right now.

**Comment by exp153** [comment]
> Not sure if this is what you mean, but, there is a permission `citizenscmd.use`, that you can negate to the ranks you don't want to use the NPC, and there is also a price option that you can set to the NPC.
> If you're talking about per NPC use permission than it's not possible right now.

Yeah, I mean per NPC use permission. Will this be added at some point?

**Comment by LichtHund** [comment]
Can definitely do!

**Comment by LichtHund** [comment]
Done! 645bbf5fd5848876cf5d78d61f4d749037104cf9 
Just update to 2.3 and it'll be working.
