### ISSUE TITLE
Command feedback

### ISSUE THREAD

**Issue by HexedHero** [LichtHund/CitizensCMD#19]
Not sure how this would be done but maybe add a command feedback setting where in your command the NPC does include
%input%
for example

  npc-2:
    cooldown: 3
    right-click-commands:
    - '[message] NPC: Which vault would you like to access?'
    - '[inputcommand] [vault.use] vault %input%'

and that would ask you which vault and you'd reply in chat with a number and then you will do the command " /vault (number) " the vault.use is also just the permission to actually use the command with the input so vaults can be tied to an NPC so players can't just do /vault 1 everywhere sorta thing.

This is just an example though.

**Comment by LichtHund** [comment]
Sounds complicated, I'll think about it though.
