### ISSUE TITLE
Wrong permission Name for /npcmd list

### ISSUE THREAD

**Issue by valeredev** [LichtHund/CitizensCMD#2]
Hello,

I use LuckPerms as PermissionManager.

CitizenCMD is 2.1.

It seems permission for cmd list is misspelled. Here  my luckperm report:

![image](https://user-images.githubusercontent.com/42415928/44749521-fe5bf300-ab12-11e8-9dfd-1e7f11baa5aa.png)

It seems the permission for list is citizescmd.list and not citizenscmd.list

**Comment by LichtHund** [comment]
Small mistake on my part, I'll roll out an update to fix that soon.
Thank you for the report!

**Comment by LichtHund** [comment]
Fixed on 094e7c2cd08d06fd139117c063b349fcfdf7f5e1.
