### ISSUE TITLE
Cooldown should be for every individual command added, instead of the same for all commands

### ISSUE THREAD

**Issue by dansuh** [LichtHund/CitizensCMD#22]
Title basically, I'd like to give a different cooldown to each command I have bound to an NPC. For example: **/npcmd cooldown left/right 1/2/3/etc (cooldown number here)**. The following would also work: **/npcmd cooldown all (cooldown number here)**  which sets the cooldown to that number for **all** added commands, so you wouldn't have to give each one a cooldown individually, should you need to have all commands be the same cooldown.

**Comment by LichtHund** [comment]
Sounds complex to add, but I can probably do it.
Though if I did I'd probably make the default for all and then an option for select command, for example:
_/npcmd cooldown_ 5 would be all and _/npcmd cooldown left 2_ would be specific.
