### ISSUE TITLE
Can't confirm/cancel payment

### ISSUE THREAD

**Issue by NilsMoller** [LichtHund/CitizensCMD#24]
**Describe the bug**
After adding a price to the npc, i can click them to use them, it shows me a message saying to shift click for confirmation or cancellation and that it will expire in 15 seconds. However shift clicking (either left or right) it keeps giving me the message to confirm or cancel.

**To Reproduce**
1. Add command to npc
2. Add price to activate
3. Right click to use npc and activate command
4. Shift-right-click to confirm

**Expected behavior**
After shift clicking for confirmation, the command run

**Versions (please complete the following information):**
 - Citizens version: 4.0.25
 - Spigot version: 1.14.2
 - CitizensCMD version: 2.3.1
- Java version: 8

**Comment by LichtHund** [comment]
Fixed, will be on 2.3.2.
49fb50090c6fc0b18fda506374657573e30dd138
