### ISSUE TITLE
Startup console error

### ISSUE THREAD

**Issue by dodieboy** [LichtHund/CitizensCMD#30]
Got this error when startup
[CitizensCMD] Plugin CitizensCMD v2.3.2 has failed to register events for class me.mattstudios.citizenscmd.listeners.NPCListener because net/citizensnpcs/api/event/NPCCloneEvent does not exist.

 - Citizens 2.0.24 (1.13.2 BETA #2)
 - Paper Spigot 1.13.2
 - CitizensCMD 2.3.2
- Java 8

**Comment by dodieboy** [comment]
But the plugin still working fine for me

**Comment by LichtHund** [comment]
You have to update Citizens to 2.0.25.

**Comment by dodieboy** [comment]
which version of citizen CMD support citizen 2.0.24? cause my server is 1.13.2, 2.0.25 only support 1.14+

**Comment by LichtHund** [comment]
This 2.0.25 should work on 1.13 just as fine as on new versions.
https://i.imgur.com/f1dUGa5.png
You can download here:
https://ci.citizensnpcs.co/job/Citizens2/1733/artifact/dist/target/Citizens-2.0.25-b1733.jar

**Comment by dodieboy** [comment]
hey thanks, have try it out, it work. saw the author say they make the plugin backwards-incompatible so i think the update for 1.14 will drop support for lower version
