### ISSUE TITLE
Setting a price, Right/Left click dousnt matter it always right clicks.

### ISSUE THREAD

**Issue by TomLewis** [LichtHund/CitizensCMD#34]
Im setting up a merchant, that if you left click i want to send the player a message, and right click will activate the payment, the problem is, if you set a payment you can no longer left click, it will right click and then it will run the left click command! This makes no sense, should the price have left/right click setting?

**Comment by LichtHund** [comment]
If you right click, then confirm the payment it'll run the right click command.
If you left click, then confirm the payment it'll run the left click command.
https://i.imgur.com/L62NtR2.png
You want it to do different things accordingly? Like payment on the left but not on the right?

**Comment by TomLewis** [comment]
Yeah, being able to set which set of commands get the payment, also you cant set the order of the payment, like you cant have a message first, payment and then another message if they confirm it, which you would have with an NPC to check what you are doing, otherwise you need to put signs everywhere. maybe the price should be part of /npcmd add price 5, then we can order it and set it to L/R.

**Comment by LichtHund** [comment]
The main purpose of the price was just to make it so you can pay for it commands.
But I like this idea, but it means rewriting a quite a bit of the system and how it works.
So I could probably do it, just don't know any time frame for it.

**Comment by TomLewis** [comment]
No sweat, its more of a logical design than working, then it follows the same pattern as what you already have with orders etc! 
If its a lot of effort maybe think of your add system as a module system, like if you wanted to add more things to the order of commands run in order, how would you do it, that way if someone wants to create an addon to it, they could do it via a module/extension.
