### ISSUE TITLE
error in console and plugin stop working

### ISSUE THREAD

**Issue by dedsec85** [LichtHund/CitizensCMD#35]
greetings
i get this error in console and npcs in game doesn't respond

[Server] Server thread/INFO [CitizensCMD] Enabling CitizensCMD v2.4
04.10 11:08:34 [Server] Server thread/ERROR Error occurred while enabling CitizensCMD v2.4 (Is it up to date?)
04.10 11:08:34 [Server] INFO java.lang.NoSuchMethodError: org.apache.commons.io.FileUtils.copyInputStreamToFile(Ljava/io/InputStream;Ljava/io/File;)V
04.10 11:08:34 [Server] INFO at me.mattstudios.citizenscmd.utility.YamlUtils.copyDefaults(YamlUtils.java:25) ~[?:?]
04.10 11:08:34 [Server] INFO at me.mattstudios.citizenscmd.CitizensCMD.onEnable(CitizensCMD.java:89) ~[?:?]
04.10 11:08:34 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-94af569-a3fdef8]
04.10 11:08:34 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

**Comment by LichtHund** [comment]
Hey! This was an error occurring when I first released the update. Can you try to re download it from Spigot? I did a hot fix that should fix it.

**Comment by dedsec85** [comment]
thank you for your fast answer i did as you instructed and it fixed my problem
