### ISSUE TITLE
Pull-request offer: Czech Localization

### ISSUE THREAD

**Issue by dusekdan** [LichtHund/CitizensCMD#36]
Hello,

as you probably know, October is a [Hacktoberfest month](https://hacktoberfest.digitalocean.com) and I would like to make a contribution to your project.

I am a native Czech language speaker so I could prepare a localized Czech language file and start a pull request with my changes. Does it sound like something you would be interested in?

If you don't know about the _Hacktoberfest initiative_, then it is a month-long even when developers try to contribute as much as possible into open-source projects and their successful pull requests are counted. For a pull request to be counted towards my Hacktoberfest profile, it must be merged during October, but the sooner the better.

I will prepare a localization file hopefully today or in the upcoming two days and send a pull request, which I hope you will accept.

**Comment by LichtHund** [comment]
Happy to help with Hacktoberfest!
And thank you for the contribution!
