### ISSUE TITLE
Crash with CitizensCMD

### ISSUE THREAD

**Issue by jere62smi** [LichtHund/CitizensCMD#40]
Hello,
since the 1.14 implementation, I noticed with random crashes with CitizensCMD indication in the crashlog.
Currently my server uses paper-87 in 1.15.2
Please resolve this if possible.
http://bin.mc-imperia.fr/KEeHbh65hg

**Comment by LichtHund** [comment]
In nowhere in this error there is any indication of this being caused by CitizensCMD, this is a Citizens crash.

**Comment by jere62smi** [comment]
Indeed it comes from more citizens, I will postpone this.
