### ISSUE TITLE
npc wont do a command

### ISSUE THREAD

**Issue by DiamondDom** [LichtHund/CitizensCMD#42]
i cant get it so that when i click it it will take me to my creative plot server even tho i have set up a custom camand that is /creativeserver and it works for the player but wont work with the npc how do i make it work

**Comment by LichtHund** [comment]
Have you tried `/npcmd add server creativeservername`?

**Comment by DiamondDom15** [comment]
would it work because it is my own server

**Comment by LichtHund** [comment]
`server` is to swap servers in a Bungee network

**Comment by DiamondDom15** [comment]
oh ok but no i have done it it will not let me click on the npc

**Comment by LichtHund** [comment]
Can you join the discord server? Github is not a good place to give support https://discord.gg/4fqu2Y

**Comment by DiamondDom15** [comment]
ok
