### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by catonato** [LichtHund/CitizensCMD#44]
I am very new to making servers. I know that since I am using luckperms, people need permissions to do different things. What I know about Citizens is that a player needs the permission. citizens.npc.talk, and citizen.npc.text, to use the NPCs. When I gave the default rank those permissions, people with the rank still can't use the NPC's. **Please help!**

**Comment by LichtHund** [comment]
This is CitizensCMD, your question is about Citizens.
