### ISSUE TITLE
Bug on reload command

### ISSUE THREAD

**Issue by sadoj-kuro** [LichtHund/CitizensCMD#6]
**Describe the bug**
When we perform a /npcmd reload an error occurs

**To Reproduce**
1. execute /npcmd reload

**LOGS**
https://pastebin.com/pNuYbDbH

**Versions (please complete the following information):**
 - Citizens version: 2.0.24
 - Spigot version: 1.13.1
 - CitizensCMD version: 2.1
- Java version: 8

**Comment by LichtHund** [comment]
Did you change anything on the config or on any language file?

**Comment by sadoj-kuro** [comment]
just adding a french YML file on folder and setting "FR" on config file

**Comment by LichtHund** [comment]
Yeah that's the problem, the file needs to be added manually by me to be supported, but I'll try to make that easier so just making the file will do it.

**Comment by sadoj-kuro** [comment]
i'm waiting to a update for using my fr.yml,

**Comment by LichtHund** [comment]
I'll try to update fast, for now if you wanna use it in french try copying the file you made and paste it on the another language file and use it.

**Comment by sadoj-kuro** [comment]
yeah thank ^^
