### ISSUE TITLE
Time bug

### ISSUE THREAD

**Issue by Rosu-Catalin** [LichtHund/CitizensCMD#7]
**Describe the bug**
So, the issue is, when I right click the npc, says https://gyazo.com/f940ed7affbde7ec6855a971f4971863.

**To Reproduce**
Dont't have errors.

**Expected behavior**

**Screenshots**
https://gyazo.com/f940ed7affbde7ec6855a971f4971863

**Versions (please complete the following information):**
 - Citizens version 2.0.22-SNAPSHOT (build 1487)
 - Spigot version 1.12.2
 - CitizensCMD version 2.1
- Java version 8

**Additional context**

**Comment by Sikatsu** [comment]
Same issue here.

**Comment by LichtHund** [comment]
Hopefully fixed on: f115d9e330126320a29e3cd72f5ad077de0cd566

**Comment by LadyHaley** [comment]
Hey, I have still been getting this bug
![image](https://user-images.githubusercontent.com/3754909/59963800-a677f800-953b-11e9-93f7-4139dfe3466d.png)
I am using the latest version on spigot right now, do i need to reset my config?

**Comment by LichtHund** [comment]
Hello @LadyHaley You might need to stop the server and delete the cooldowns.yml file.
